# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "848175b435c6564aca4bb8b81696bd8d"
application_url = "https://tiles-usage-immigration-baseline.trycloudflare.com"
embedded = true
name = "convert-tracking-app"
handle = "convert-tracking-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lme-checkout.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order_created"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/app/product_created"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://convert-tracking-app.vercel.app/auth/callback",
  "https://convert-tracking-app.vercel.app/auth/shopify/callback",
  "https://convert-tracking-app.vercel.app/api/auth/callback"
]

[pos]
embedded = false
