# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a790f0926e4a6392b217838e8f659e6a"
application_url = "https://alleged-edges-scholarships-sleep.trycloudflare.com"
embedded = true
name = "convert Tracking App"
handle = "convert-tracking-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lme-checkout.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/app/order_created"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products,read_all_orders"

[auth]
redirect_urls = [
  "https://alleged-edges-scholarships-sleep.trycloudflare.com/auth/callback",
  "https://alleged-edges-scholarships-sleep.trycloudflare.com/auth/shopify/callback",
  "https://alleged-edges-scholarships-sleep.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
